export type GameMechanic = "memory" | "sequence" | "reaction";

export type GameDefinition = {
  slug: string;
  title: string;
  category: string;
  description: string;
  mechanic: GameMechanic;
  exerciseIntro: string;
  sequenceItems?: string[];
  reactionTarget?: string;
  reactionDecoys?: string[];
};

export const gameLibrary: GameDefinition[] = [
  {
    slug: "jogodolabirinto",
    title: "Jogo do Labirinto",
    category: "visuoespacial/planejamento",
    description: "Planeje uma rota, antecipe etapas e exercite a orientação visuoespacial em um desafio breve.",
    mechanic: "sequence",
    exerciseIntro: "Organize as decisões que ajudam a encontrar uma saída com menos tentativas.",
    sequenceItems: ["Observar o mapa", "Localizar a saída", "Planejar a rota", "Percorrer o caminho"],
  },
  {
    slug: "caca-rapida",
    title: "Caça-Rápida Verbal",
    category: "linguagem/atenção",
    description: "Encontre palavras-alvo com agilidade e estimule atenção, linguagem e acesso lexical.",
    mechanic: "reaction",
    exerciseIntro: "Toque apenas quando a palavra-alvo aparecer entre palavras parecidas.",
    reactionTarget: "CÉREBRO",
    reactionDecoys: ["CÉU", "CEREJA", "CÉLULA", "CÉLEBRE"],
  },
  {
    slug: "desafiohanoi",
    title: "Desafio Hanói",
    category: "funções executivas",
    description: "Exercite lógica, planejamento e resolução de problemas inspirados na Torre de Hanói.",
    mechanic: "sequence",
    exerciseIntro: "Coloque as etapas de uma estratégia eficiente na ordem correta.",
    sequenceItems: ["Observar os discos", "Definir o pino de destino", "Mover o menor disco", "Liberar o disco maior", "Revisar a estratégia"],
  },
  {
    slug: "resta-um-raciocinio-visual",
    title: "Resta Um",
    category: "raciocínio visual",
    description: "Treine lógica, atenção e antecipação de movimentos com um desafio inspirado no clássico Resta Um.",
    mechanic: "sequence",
    exerciseIntro: "Organize o ciclo de decisões usado para planejar cada jogada.",
    sequenceItems: ["Observar os espaços", "Escolher uma peça", "Antecipar o salto", "Retirar a peça pulada", "Reavaliar o tabuleiro"],
  },
  {
    slug: "sequênciainteligente",
    title: "Sequência Inteligente",
    category: "raciocínio lógico",
    description: "Descubra padrões e exercite lógica, memória de trabalho e atenção com sequências progressivas.",
    mechanic: "sequence",
    exerciseIntro: "Identifique a regra e selecione os números do menor para o maior.",
    sequenceItems: ["2", "4", "8", "16", "32"],
  },
  {
    slug: "desafiodascores",
    title: "Desafio das Cores",
    category: "atenção/velocidade",
    description: "Exercite atenção seletiva, velocidade e controle mental diante de informações concorrentes.",
    mechanic: "reaction",
    exerciseIntro: "Mantenha o foco e toque somente quando a cor-alvo aparecer.",
    reactionTarget: "VERDE",
    reactionDecoys: ["AZUL", "ROXO", "AMARELO", "VERMELHO"],
  },
  {
    slug: "caca-fantasmas-agilidade-atencao",
    title: "Reflexo Fantasma",
    category: "atenção/velocidade",
    description: "Treine foco visual, agilidade mental e tempo de resposta em uma rodada curta e dinâmica.",
    mechanic: "reaction",
    exerciseIntro: "Espere o fantasma-alvo e responda sem se deixar levar pelos distratores.",
    reactionTarget: "👻",
    reactionDecoys: ["🌙", "🕯️", "🦇", "⭐"],
  },
  {
    slug: "torredelondresdigital",
    title: "Torre de Londres Digital",
    category: "planejamento",
    description: "Exercite planejamento, raciocínio e memória de trabalho antes de executar cada movimento.",
    mechanic: "sequence",
    exerciseIntro: "Organize o processo de solução antes de começar a agir.",
    sequenceItems: ["Comparar início e objetivo", "Contar movimentos", "Escolher a primeira peça", "Executar o plano", "Conferir o resultado"],
  },
  {
    slug: "quebra-cabeçaemoji",
    title: "Quebra-cabeça Emoji",
    category: "percepção visual",
    description: "Treine percepção visual, atenção e organização espacial em uma atividade leve com emojis.",
    mechanic: "sequence",
    exerciseIntro: "Monte a estratégia usada para reconstruir uma imagem por partes.",
    sequenceItems: ["Observar a imagem", "Encontrar as bordas", "Agrupar partes parecidas", "Preencher o centro", "Conferir o conjunto"],
  },
  {
    slug: "afirmou-bateu",
    title: "Afirmou, Bateu!",
    category: "atenção/velocidade",
    description: "Compare estímulos com rapidez e exercite foco, velocidade de decisão e autocontrole.",
    mechanic: "reaction",
    exerciseIntro: "Toque apenas quando a afirmação-alvo surgir; ignore as alternativas.",
    reactionTarget: "COMBINA",
    reactionDecoys: ["DIFERENTE", "TALVEZ", "INVERTIDO", "NÃO COMBINA"],
  },
  {
    slug: "memóriamix",
    title: "Memória Mix",
    category: "memória",
    description: "Encontre pares e estimule memória visual e atenção em uma atividade que pode ser repetida.",
    mechanic: "memory",
    exerciseIntro: "Vire duas cartas por vez, memorize suas posições e encontre todos os pares.",
  },
  {
    slug: "emojialvo",
    title: "Emoji Alvo",
    category: "atenção/memória",
    description: "Mantenha um emoji em mente e responda somente quando ele reaparecer entre os distratores.",
    mechanic: "reaction",
    exerciseIntro: "Memorize o alvo e toque nele quando aparecer.",
    reactionTarget: "🎯",
    reactionDecoys: ["🎨", "🎈", "🎲", "🎸"],
  },
  {
    slug: "intrusodaspalavras",
    title: "Intruso das Palavras",
    category: "linguagem/raciocínio",
    description: "Identifique o item que não pertence ao grupo e exercite categorização, linguagem e atenção.",
    mechanic: "reaction",
    exerciseIntro: "As frutas são distratores: toque apenas quando aparecer a palavra intrusa.",
    reactionTarget: "BICICLETA",
    reactionDecoys: ["MAÇÃ", "BANANA", "UVA", "MANGA"],
  },
  {
    slug: "cliquenomomentocerto",
    title: "Clique no Momento Certo",
    category: "velocidade/controle inibitório",
    description: "Treine precisão, atenção sustentada e controle do impulso esperando o estímulo correto.",
    mechanic: "reaction",
    exerciseIntro: "Resista aos sinais de espera e toque somente quando o comando aparecer.",
    reactionTarget: "AGORA!",
    reactionDecoys: ["ESPERE", "ATENÇÃO", "PREPARE-SE", "CALMA"],
  },
  {
    slug: "cacacirculos",
    title: "Jogo do Círculo Rápido",
    category: "atenção/velocidade",
    description: "Estimule rastreio visual e velocidade de resposta localizando o círculo-alvo entre formas próximas.",
    mechanic: "reaction",
    exerciseIntro: "Toque no círculo quando ele aparecer e ignore as outras formas.",
    reactionTarget: "●",
    reactionDecoys: ["■", "▲", "◆", "✦"],
  },
  {
    slug: "memorianumerica",
    title: "Memória Numérica",
    category: "memória de trabalho",
    description: "Exercite atenção e memória de trabalho mantendo informações ativas durante uma tarefa curta.",
    mechanic: "memory",
    exerciseIntro: "Use os pares como uma variação visual para aquecer a memória de trabalho.",
  },
  {
    slug: "buscadosímbolo",
    title: "Busca do Símbolo",
    category: "atenção/percepção visual",
    description: "Localize um símbolo de referência e exercite percepção visual, atenção e velocidade.",
    mechanic: "reaction",
    exerciseIntro: "Memorize o símbolo-alvo e responda somente quando ele aparecer.",
    reactionTarget: "✦",
    reactionDecoys: ["✚", "◆", "▲", "■"],
  },
  {
    slug: "ordem-das-acoes",
    title: "Ordem das Ações",
    category: "funções executivas",
    description: "Organize etapas na sequência adequada e estimule planejamento, lógica e memória de trabalho.",
    mechanic: "sequence",
    exerciseIntro: "Coloque uma rotina simples na ordem em que ela acontece.",
    sequenceItems: ["Separar os ingredientes", "Preparar a receita", "Servir a refeição", "Guardar o que sobrou", "Lavar a louça"],
  },
  {
    slug: "palavra-emoji",
    title: "Palavra & Emoji",
    category: "linguagem/memória",
    description: "Associe significados e imagens para exercitar linguagem, memória e atenção visual.",
    mechanic: "memory",
    exerciseIntro: "Encontre pares visuais como aquecimento para associações entre palavra e imagem.",
  },
  {
    slug: "sequênciadascores",
    title: "Sequência das Cores",
    category: "memória/atenção",
    description: "Memorize estímulos visuais e exercite atenção enquanto busca combinações correspondentes.",
    mechanic: "memory",
    exerciseIntro: "Observe cada carta e memorize onde as formas aparecem para completar os pares.",
  },
];

export const gameBySlug: Record<string, GameDefinition> = Object.fromEntries(
  gameLibrary.map((game) => [game.slug, game]),
);
